### ISSUE TITLE
Add overall `pipeline.cwl` referencing steps in submodules and this repo

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/multiome-rna-atac-pipeline#3]
Inspiration: https://github.com/hubmapconsortium/citeseq-pipeline/blob/main/pipeline.cwl, especially https://github.com/hubmapconsortium/citeseq-pipeline/blob/main/pipeline.cwl#L86 which uses a step from the `salmon-rnaseq` submodule

**Comment by seschultz** [comment]
https://github.com/hubmapconsortium/multiome-rna-atac-pipeline/blob/main/pipeline.cwl
